[package]
name = "stick-solo"
version = "0.0.0"
authors = ["Yashasvi Sriram Patkuri <yash.3997@gmail.com>"]
edition = "2018"

[dependencies]
bevy = "0.3.0"
bevy_fly_camera = "0.5.0"
rand = "0.7.3"
nalgebra = "0.23.0"
